[platformio]
default_envs = esp8266

[env:esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_flags =
  -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY

[env:diagnostic]
extends = env:esp8266
build_flags =
  ${env:esp8266.build_flags}
  -D SERIAL_DIAGNOSTICS=1
